# Generated by Django 4.1.3 on 2022-11-15 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0004_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.FloatField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicdb.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicdb.artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicdb.genre')),
                ('playlist', models.ManyToManyField(to='musicdb.playlist')),
            ],
        ),
    ]
