# Generated by Django 4.1.3 on 2022-11-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0005_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(to='musicdb.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='musicdb.artist'),
        ),
    ]
