# Generated by Django 4.1.3 on 2022-11-17 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0006_remove_song_album_remove_song_artist_song_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicdb.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(related_name='track_list', to='musicdb.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(related_name='artist_list', to='musicdb.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genre_list', to='musicdb.genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(related_name='playlist_list', to='musicdb.playlist'),
        ),
    ]
